---
- name: Create user home directories
  file:
    path: ~/{{ item }}
    state: directory
    mode: '700'
  loop: "{{ homedirs }}"
  tags:
    - homedirs

- name: Delete default home folders created by XDG
  file:
    path: ~/{{ item }}
    state: absent
  loop:
    - Desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos
  tags:
    - homedirs
