#!/usr/bin/env bash

#
# Load variables
#

source ~/.config/bspwm/scripts/vars.sh

#
# Start up applications
#

~/.config/bspwm/scripts/autostart.sh

#
# Base config
#

bspc monitor -d                   1 2 3 4 5

bspc config border_width          1
bspc config window_gap            8
bspc config split_ratio           0.50
bspc config focus_follows_pointer true

#
# Colors
#

bspc config normal_border_color   "#23272e"
bspc config focused_border_color  "#51565e"
bspc config presel_feedback_color "#060e1a"

#
# Rules
#

# Quake terminal
bspc rule -a 'Alacritty:Quake' \
    sticky=on \
    state=floating \
    border=off \
    hidden=on \
    layer=above \
    rectangle=${quake_dimensions}

# Floating clients
bspc rule -a Pavucontrol state=floating
bspc rule -a feh         state=floating
