---
- name: Configure Kali Linux
  hosts: all
  connection: local
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - role: base
    - role: hostname
    - role: timezone
    - role: editor
    - role: user
