galaxy_info:
  author: github.com/hakbyte
  description: Configure VirtualBox Guest OS
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - bullseye
dependencies:
  - role: system/apt
