---
- name: Install base packages
  apt:
    name: "{{ pkg }}"
  tags:
    - base

- name: Install base packages (*.deb)
  apt:
    deb: "{{ item }}"
  loop: "{{ deb }}"
  tags:
    - base
    - deb

- name: Push keyboard input options
  template:
    src: keyboard.j2
    dest: /etc/default/keyboard
    mode: '644'
  tags:
    - base

- name: Make /usr/bin/python point to Python3
  apt:
    name: python-is-python3
  tags:
    - base

- name: Change root shell to Zsh
  user:
    name: root
    shell: /usr/bin/zsh
  tags:
    - base

- name: Set mouse cursor size
  lineinfile:
    line: "XCURSOR_SIZE=32"
    path: /etc/environment
    create: yes
    mode: '644'
  tags:
    - base

- name: Download wallpaper
  get_url:
    url: "{{ wallpaper.url }}"
    dest: "{{ wallpaper.dest }}/{{ wallpaper.url | basename }}"
    checksum: "{{ wallpaper.checksum }}"
    mode: '644'
  tags:
    - base
