galaxy_info:
  author: github.com/hakbyte
  description: Allow users in the sudo group to run all commands
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - bullseye
