---
- name: Deploy dotfiles for Kali Linux
  hosts: all
  connection: local
  roles:
    - role: dots/zsh
    - role: dots/tmux
    - role: dots/alacritty
    - role: dots/homedirs
    - role: dots/xdg
    - role: dots/neovim
