---
- name: Deploy dotfiles for Kali Linux
  hosts: all
  connection: local
  vars_files:
    - ../vars/all.yml
  roles:
    - role: dots/x
    - role: dots/zsh
    - role: dots/tmux
    - role: dots/alacritty
    - role: dots/homedirs
    - role: dots/xdg
    - role: dots/neovim
    - role: dots/rofi
    - role: dots/picom
    - role: dots/polybar
    - role: dots/sxhkd
    - role: dots/bspwm
