---
- name: Configure Kali Linux
  hosts: all
  connection: local
  become: yes
  vars_files:
    - ../vars/all.yml
  roles:
    - role: system/base
    - role: system/hostname
    - role: system/nameservers
    - role: system/timezone
    - role: system/sudo
    - role: system/editor
    - role: system/user
    - role: system/vbox
      when: target is defined and target == "vbox"
