galaxy_info:
  author: github.com/hakbyte
  description: Install bspwm and its dependencies
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - bullseye

dependencies:
  - role: apt
  - role: base
